<a href="https://colab.research.google.com/github/Kiranwaghmare123/KD/blob/master/Numpy_Pandas_Matplotlib_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Tutorial**

# data.txt
1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5

3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12

1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88


In [3]:
#Import statements
import numpy as np

In [4]:
a=np.array([1,2,3])
b=np.array([
    [1,1],
    [1,1]
])
c=np.array([1,2,3],dtype="int16")

In [5]:
print(a)
print(b)
print(c)
print('-------')
print(a.ndim)
print(b.ndim)
print(c.ndim)
print('-------')
print(a.shape)
print(b.shape)
print(c.shape)

[1 2 3]
[[1 1]
 [1 1]]
[1 2 3]
-------
1
2
1
-------
(3,)
(2, 2)
(3,)


**Numpy Benefits**
*   Fixed Type
*   Contigious memory






In [7]:
#get type
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int16


In [8]:
#get size - size of each item (8)
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

8
8
2


In [9]:
#get total size - total space used (8)
print(a.size * a.itemsize)
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

24
24
32
6


In [11]:
arr = [range(1,5), range(5,9)] #List of Lists
e = np.array(arr) #2nd array
print(e)
x = e.tolist() # convert array back to list
print(type(x))

[[1 2 3 4]
 [5 6 7 8]]
<class 'list'>


**Adding and removing elements from numpy arrays**

In [14]:
a = np.array(np.arange(24)).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
b = np.append(a,[5,6,7,8])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  5,  6,  7,  8])

In [16]:
b.shape

(28,)

In [19]:
b.reshape((7, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [20]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
c = np.array(np.arange(24).reshape((2,3,4)) * 10 + 3)
c

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [24]:
np.append(a,c,axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [26]:
np.append(a,c,axis=0).shape

(4, 3, 4)

In [33]:
np.append(a,c, axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [34]:
np.append(a,c,axis=1).shape

(2, 6, 4)

In [35]:
np.append(a,c, axis=2)

array([[[  0,   1,   2,   3,   3,  13,  23,  33],
        [  4,   5,   6,   7,  43,  53,  63,  73],
        [  8,   9,  10,  11,  83,  93, 103, 113]],

       [[ 12,  13,  14,  15, 123, 133, 143, 153],
        [ 16,  17,  18,  19, 163, 173, 183, 193],
        [ 20,  21,  22,  23, 203, 213, 223, 233]]])

In [37]:
np.append(a,c, axis=2).shape

(2, 3, 8)

In [38]:
after_insert_array = np.insert(c,1,444, axis=0)
after_insert_array

array([[[  3,  13,  23,  33],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[444, 444, 444, 444],
        [444, 444, 444, 444],
        [444, 444, 444, 444]],

       [[123, 133, 143, 153],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [39]:
after_insert_array = np.insert(c,1,444,axis=1)
after_insert_array

array([[[  3,  13,  23,  33],
        [444, 444, 444, 444],
        [ 43,  53,  63,  73],
        [ 83,  93, 103, 113]],

       [[123, 133, 143, 153],
        [444, 444, 444, 444],
        [163, 173, 183, 193],
        [203, 213, 223, 233]]])

In [41]:
after_insert_array = np.insert(c,1,444,axis=2)
after_insert_array

array([[[  3, 444,  13,  23,  33],
        [ 43, 444,  53,  63,  73],
        [ 83, 444,  93, 103, 113]],

       [[123, 444, 133, 143, 153],
        [163, 444, 173, 183, 193],
        [203, 444, 213, 223, 233]]])

In [43]:
d=np.empty(c.shape)
np.copyto(d,c)
d

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [163., 173., 183., 193.],
        [203., 213., 223., 233.]]])

In [44]:
np.delete(d,1,axis=0)

array([[[  3.,  13.,  23.,  33.],
        [ 43.,  53.,  63.,  73.],
        [ 83.,  93., 103., 113.]]])

In [45]:
np.delete(d,1,axis=1)

array([[[  3.,  13.,  23.,  33.],
        [ 83.,  93., 103., 113.]],

       [[123., 133., 143., 153.],
        [203., 213., 223., 233.]]])

In [46]:
np.delete(d,1,axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

In [47]:
np.delete(d,1,axis=2)

array([[[  3.,  23.,  33.],
        [ 43.,  63.,  73.],
        [ 83., 103., 113.]],

       [[123., 143., 153.],
        [163., 183., 193.],
        [203., 223., 233.]]])

**Accessing/Changing specific elements, rows, columns, etc**

In [48]:
a = np.array([[1,2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [49]:
# get a specific element [r, c]
print(a[1, 5])
print(a[1][5])
print(a[1][-2])


13
13
13


In [50]:
#  get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
# get a specific col
a[:, 2]


array([ 3, 10])

In [55]:
# getting fancy [startindex: endindex: stepsize]
print(a[0, 1:6:2])

[2 4 6]


In [56]:
#Changing element(s)
a[1,5] = 20
print(a)
print('---------')
a[:, 2] = 5
print(a)
print('---------')
a[:,2] = [1, 2]
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
---------
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
---------
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [57]:
a= np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(a)
print('------------')
print(a.shape)

#think of number of rows as original number of rows
#inside each box columns become rows and depth becomes columns
#tink of it as [1,2] at at position a[0,0]

#Numpy's order for printig n-dimensional arrays is that the last slowest 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
------------
(2, 2, 2)


In [58]:
print(a[0,0])
print(a[0,1])
print(a[1,0])
print(a[1,1])

#get specific element
print(a[0,1,1])

[1 2]
[3 4]
[5 6]
[7 8]
4


In [59]:
# replace

a[:, 1, :] = [[10,11],[12,13]]
print(a)
print('-----------')

a[0, 1, :] = [99,98]
print(a)

[[[ 1  2]
  [10 11]]

 [[ 5  6]
  [12 13]]]
-----------
[[[ 1  2]
  [99 98]]

 [[ 5  6]
  [12 13]]]


**Initializing different type of arrays**

In [61]:
#all 0's matrix
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
#all 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [65]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [66]:
#any other number (full_like)
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a,8)

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [67]:
# random decimal numbers
np.random.rand(4,2,3)

array([[[0.46532789, 0.38118664, 0.74008862],
        [0.93404053, 0.37484192, 0.92885601]],

       [[0.06795414, 0.0680727 , 0.36444648],
        [0.16147555, 0.37261316, 0.46825648]],

       [[0.84522268, 0.23936176, 0.38455569],
        [0.5482537 , 0.85656253, 0.87727173]],

       [[0.12206647, 0.32191211, 0.27378656],
        [0.9159989 , 0.48158567, 0.04244544]]])

In [68]:
np.random.random_sample(a.shape)

array([[0.48967732, 0.47785215, 0.30636349, 0.20890771, 0.27289285,
        0.35478064, 0.80649152],
       [0.1584656 , 0.81318135, 0.96977893, 0.74914422, 0.88157142,
        0.41838737, 0.59202473]])

In [70]:
#random integer values
print(np.random.randint(7))
print(np.random.randint(7, size=(3,3)))

6
[[1 3 3]
 [0 0 2]
 [6 5 6]]


In [71]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
print(np.logspace(0,3,4)) #10^0 to 10^3 (incusive) with 4 points

[   1.   10.  100. 1000.]


In [73]:
#repeat an array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)
print('---------')
r2= np.repeat(arr, 3, axis=1)
print(r2)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
---------
[[1 1 1 2 2 2 3 3 3]]


In [74]:
#Creating a customized matrix
output = np.ones((5,5))
print(output)
print('-----------')

z = np.zeros((3,3))
z[1,1] = 9
print(z)
print('---------------')

output[1:4,1:4]=z
print(output)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-----------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [76]:
#careful while copying
a=np.array([1,2,3])
b=a#just points
b[0]=100
print(a)
print(b)


a = np.array([1, 2, 3])
b = a.copy()
b [0]= 100
print(a)
print(b)


[100   2   3]
[100   2   3]
[1 2 3]
[100   2   3]


In [77]:
#adding an axis
a=np.array([0,1])
a_col = a[:, np.newaxis]
print(a_col)





[[0]
 [1]]


In [79]:
a_col.T

array([[0, 1]])

In [82]:
#flattern array
#always return a flat copy of the original array
arr = np.arange(10,dtype=float).reshape((2,5))
arr_flat = arr.flatten()
arr_flat[0] = 33

print(arr)
print(arr_flat)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [84]:
#Ravel: returns a view of te original array whenever possible.
arr_flt = arr.ravel()
arr_flt[0] = 33

print(arr)
print(arr_flt)

[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [85]:
#creating evenly spaced number over an specified interval

np.linspace(start =0, stop=50, num=10)
np.linspace(5,15,10)
mylinspace = np.linspace(5,15,9,retstep=True)
mylinspace


(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

**Mathematics**

In [88]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [89]:
a+2

array([3, 4, 5, 6])

In [90]:
a-2

array([-1,  0,  1,  2])

In [91]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [92]:
b=np.array([1,0,1,0])

In [93]:
a+b

array([2, 2, 4, 4])

In [94]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

**Linear algebra**

In [96]:
my_first_matrix = np.matrix([[3,1,4],[1,5,9],[2,6,5]])
my_first_matrix

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [97]:
my_first_matrix.T

matrix([[3, 1, 2],
        [1, 5, 6],
        [4, 9, 5]])

In [98]:
my_first_matrix.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

In [101]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [102]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [104]:
c=np.identity(4) # or p.eye(5)
print(np.linalg.det(c))

1.0


In [106]:
# Solve simultaneous linear equations
right_hand_side = np.matrix([[11],
                             [22],
                             [33]])

my_first_inverse = my_first_matrix.I


In [109]:
solution = my_first_inverse * right_hand_side

solution

matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [111]:
#more efficient for large matrices
from numpy.linalg import solve
solve(my_first_matrix,right_hand_side)


matrix([[ 2.93333333],
        [ 5.13333333],
        [-0.73333333]])

In [113]:
# Compute the eigenvalues and eigenvectors
from numpy.linalg import eig
eig(my_first_matrix)

(array([13.08576474,  2.58000566, -2.66577041]),
 matrix([[-0.31542644, -0.95117074, -0.32372474],
         [-0.72306109,  0.30781323, -0.70222933],
         [-0.61456393,  0.02291827,  0.63409484]]))

**Statistics**

In [116]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
print(np.min(stats, axis=0))
print(np.min(stats, axis=1))

print(np.max(stats, axis=0))
print(np.max(stats, axis=1))

[1 2 3]
[1 4]
[4 5 6]
[3 6]


In [118]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [119]:
rnd=np.random.randn(4,2) # random normals in 4X2 array
print(rnd.mean())
print(rnd.std())
print(rnd.argmin()) # index of minimum element
print(rnd.sum())
print(rnd.sum(axis=0)) # sum of columns
print(rnd.sum(axis=1)) # sum of rows

-0.20157312557013393
1.0200789987418581
1
-1.6125850045610715
[-2.23399201  0.621407  ]
[-2.1122827   0.72744939  1.03074437 -1.25849608]


***https://github.com/veb-101/Numpy-Pandas-Matplotlib-Tutorial/blob/master/numpy/Numpy%20basic%20tutorial.ipynb***