In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.12.0'

# Part 1 - Data Preprocessing

# Importing the dataset

In [4]:
dataset = pd.read_csv('D:/Test/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding categorical data

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Building the ANN

# Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

# Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6302 - accuracy: 0.6636
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4665 - accuracy: 0.8039
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4405 - accuracy: 0.8104
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4223 - accuracy: 0.8191
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4068 - accuracy: 0.8265
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8339
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3790 - accuracy: 0.8393
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3694 - accuracy: 0.8431
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3625 - accuracy: 0.8465
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3575 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3306 - accuracy: 0.8634
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3302 - accuracy: 0.8648
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3302 - accuracy: 0.8640
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3300 - accuracy: 0.8659
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3302 - accuracy: 0.8650
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3298 - accuracy: 0.8644
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3296 - accuracy: 0.8654
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3305 - accuracy: 0.8654
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3301 - accuracy: 0.8636
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3301 - accuracy: 

# Part 4 - Making the predictions and evaluating the model

# Predicting the result of a single observation

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 259ms/step
[[False]]


# Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1529   66]
 [ 206  199]]


0.864